.github/pull_request_template.md
.vscode/tasks.json

Minor infra edits

---

src/main/java/competition/Robot.java

Move AprilTagVisionSubsystem to DataFrameRefreshable

---

src/main/java/competition/Robot.java
src/main/java/competition/electrical_contract/Contract2023.java
src/main/java/competition/electrical_contract/Contract2024.java
src/main/java/competition/electrical_contract/Contract2025.java
src/main/java/competition/operator_interface/OperatorCommandMap.java
src/main/java/competition/operator_interface/OperatorInterface.java
src/main/java/competition/subsystems/drive/commands/DebugSwerveModuleCommand.java

- Fixing various bugs found when deploying 2025 code to all recent chassis
-Bugfixes in contracts
-Temporary disable of vision system for 2024 until PhotonVision version mismatch addressed

Swerve Fixes for 2023/2024/2025 Chassis

---

src/main/java/competition/electrical_contract/Contract2025.java
src/main/java/competition/electrical_contract/ElectricalContract.java
src/main/java/competition/subsystems/algae_collection/AlgaeCollectionSubsystem.java
src/main/java/competition/subsystems/arm_pivot/ArmPivotSubsystem.java
src/main/java/competition/subsystems/arm_pivot/commands/command.java

Created the subsystem for arm movement
-----

Arm Pivot Subsystem Creation

---

src/main/java/competition/simulation/ElevatorSimulator.java
src/main/java/competition/simulation/MapleSimulator.java
src/main/java/competition/simulation/SimulationConstants.java
src/main/java/competition/simulation/arm/ArmSimConstants.java
src/main/java/competition/simulation/arm/ArmSimulator.java

To simulate the arm mechanism
Modeled off the WPIlib arm example project, using all it's default values for things. This needs more work but is a start.
We need to model the encoder rotations and angles more specifically
Not tested at all yet
-----

Arm Simulation

---

src/main/java/competition/injection/modules/CommonModule.java
src/main/java/competition/subsystems/pose/PoseSubsystem.java

Integrate vision pose

---

src/main/java/competition/Robot.java
src/main/java/competition/injection/components/BaseRobotComponent.java
src/main/java/competition/subsystems/arm_pivot/ArmPivotSubsystem.java

This is an annoying extra step we need to do to get motors working in advantage kit
-----

Add Arm subsystem to be data frame refreshable

---

src/main/java/competition/simulation/ElevatorSimConstants.java
src/main/java/competition/simulation/ElevatorSimulator.java

Now that we have an ElevatorSubsystem, we can read from it to control the simulated elevator mechanism
Untested because the elevator can't actually be controlled yet
-----

Elevator in simulator: read from mock motor 

---

src/main/java/competition/simulation/arm/ArmSimConstants.java
src/main/java/competition/simulation/arm/ArmSimulator.java

Arm sim: hookup to arm motor

---

src/main/java/competition/subsystems/pose/Landmarks.java

Landmarks for reef branches, reef face centers (algae), and coral stations

---

src/main/java/competition/injection/modules/SimulatedRobotModule.java
src/main/java/competition/simulation/BaseSimulator.java
src/main/java/competition/simulation/MapleSimulator.java
src/main/java/competition/simulation/NoopSimulator.java
src/main/java/competition/simulation/Simulator.java
src/main/java/competition/subsystems/pose/PoseSubsystem.java

Photonlib: update simulated position from BaseSimulator implementation

---

src/main/java/competition/subsystems/SubsystemDefaultCommandMap.java
src/main/java/competition/subsystems/arm_pivot/commands/ArmPivotMaintainerCommand.java
src/main/java/competition/subsystems/coral_scorer/CoralScorerSubsystem.java

Created min & max values for arm maintainer.
-----

Arm maintainer

---

src/main/java/competition/subsystems/arm_pivot/ArmPivotSubsystem.java
src/main/java/competition/subsystems/elevator/ElevatorSubsystem.java

Some motor calls weren't checking the contract
-----

Fix calls to motors that aren't yet ready (per the contract)

---

src/main/java/competition/subsystems/pose/PoseSubsystem.java

Asana task URL: https://app.asana.com/0/1208731987242938/1209190708009168/f
Optionally logging the Pose3d for each camera on the robot.
-----

Log camera poses

---

src/main/java/competition/injection/components/BaseRobotComponent.java
src/main/java/competition/simulation/arm/ArmSimulator.java
src/main/java/competition/subsystems/SubsystemDefaultCommandMap.java
src/main/java/competition/subsystems/coral_arm_pivot/CoralArmPivotSubsystem.java
src/main/java/competition/subsystems/coral_arm_pivot/commands/CoralArmPivotMaintainerCommand.java
src/main/java/competition/subsystems/elevator_mechanism/SuperstructureMechanismSubsystem.java

Defined arm known positions

---

src/main/java/competition/electrical_contract/ElectricalContract.java
src/main/java/competition/subsystems/coral_arm_pivot/CoralArmPivotSubsystem.java

remove duplicate arm contract value and resolve merge conflicts

---

src/main/java/competition/subsystems/coral_arm_pivot/CoralArmPivotSubsystem.java

Created switch-cased statement for arm angles

---

src/main/java/competition/simulation/MapleSimulator.java
src/main/java/competition/simulation/coral_arm/CoralArmSimConstants.java
src/main/java/competition/simulation/coral_arm/CoralArmSimulator.java

We used to only have 1 arm, now we'll have 2!
-----

rename arm sim to coral arm sim

---

src/main/java/competition/Robot.java
src/main/java/competition/electrical_contract/Contract2025.java
src/main/java/competition/electrical_contract/ElectricalContract.java
src/main/java/competition/electrical_contract/RoboxContract.java
src/main/java/competition/subsystems/elevator/ElevatorSubsystem.java
vendordeps/LaserCAN.json

Adds the LaserCAN distance sensor to the elevator (initially disabled)
-----

Adds LaserCAN distance sensor to elevator

---

src/main/java/competition/electrical_contract/UnitTestContract2025.java
src/main/java/competition/subsystems/SubsystemDefaultCommandMap.java
src/main/java/competition/subsystems/algae_arm/AlgaeArmSubsystem.java

Slight branch

---

src/main/java/competition/electrical_contract/Contract2024.java
src/main/java/competition/injection/modules/Module2023.java
src/main/java/competition/injection/modules/Module2024.java
src/main/java/competition/injection/modules/Module2025.java
src/main/java/competition/injection/modules/RoboxModule.java
src/main/java/competition/injection/modules/SimulatedRobotModule.java
src/main/java/competition/injection/modules/UnitTestRobotModule.java

Fix apriltag subsystem injection

---

src/main/java/competition/subsystems/elevator/commands/ElevatorMaintainerCommand.java

To apply minimum power in the sim so elevator doensn't need to constantly pid towards it because of gravity
- [x ] tested in simulator
-----

 added constant power to counteract gravity in Sim, + Deleting unneeded stuff in maintainer

---

src/main/java/competition/subsystems/pose/EnumsToPose.java
src/main/java/competition/subsystems/pose/Landmarks.java

Enums to pose

---

src/main/java/competition/injection/components/BaseRobotComponent.java
src/main/java/competition/motion/TrapezoidProfileManager.java
src/main/java/competition/subsystems/elevator/commands/ElevatorMaintainerCommand.java
src/test/java/competition/motion/TrapezoidProfileManagerTest.java

Tests are good!
Added unit tests for TrapezoidalProfileManager, and added a factory class to clean it up a bit.
-----

Unit tests for TrapezoidProfileManager and add an assisted factory

---

build.gradle

Add exceptions to JaCoCo to exclude generated files

---

src/main/java/competition/electrical_contract/Contract2025.java
src/main/java/competition/electrical_contract/ElectricalContract.java
src/main/java/competition/electrical_contract/UnitTestContract2025.java
src/main/java/competition/subsystems/coral_arm_pivot/CoralArmPivotSubsystem.java

Changed the names to have coral in it
Simplifies coding
-----

Electrical changes

---

src/main/java/competition/Robot.java
src/main/java/competition/injection/components/BaseRobotComponent.java
src/main/java/competition/subsystems/coral_scorer/CoralScorerSubsystem.java
src/main/java/competition/subsystems/lights/LightSubsystem.java

Mostly a port of 2024, leaned down to remove how the data is communicated (an active topic of investigation).
I've added some of the more obvious 2025 states (like has coral or wants coral).
-----

Lightsubsystem skeleton

---

src/main/java/competition/subsystems/elevator/ElevatorSubsystem.java
src/main/java/competition/subsystems/elevator/commands/ElevatorMaintainerCommand.java

For smoother motion in elevator 
Just small changes to elevator maintainer modifying how power is set
- [x ] tested in simulator
-----

PID Via Motor Controllers & Power limits near extreme heights (This is Junyu)

---

src/test/java/competition/subsystems/GenericSubsystemTest.java

Try to fix the flaky generic subsystem test

---

src/main/java/competition/electrical_contract/Contract2025.java

Protect current from being too much
-----

CurrentProtectons

---

src/main/java/competition/Robot.java

Use the Log4j logger to indicate which DI module is in use.

---

src/test/java/competition/subsystems/drive/DriveSubsystemTest.java
src/test/java/competition/subsystems/elevator/ElevatorSubsystemTest.java

Add a couple of unit tests

---

src/main/java/competition/electrical_contract/Contract2025.java

changed elevator bottom sensor channel to 3 (Michael said it was on DIGITAL IO 3)

---

src/main/java/competition/subsystems/drive/commands/CalibrateDriveCommand.java
src/test/java/competition/subsystems/drive/DriveSubsystemDisabledTest.java

Update SCL to use Optional in the swerve drive

---

src/main/java/competition/subsystems/coral_scorer/CoralScorerSubsystem.java

Made a condition for adding a small power when the scorer has coral

---

src/main/java/competition/simulation/MotorInternalPIDHelper.java
src/main/java/competition/simulation/algae_arm/AlgaeArmSimulator.java
src/main/java/competition/simulation/coral_arm/CoralArmSimulator.java
src/main/java/competition/simulation/elevator/ElevatorSimConstants.java
src/main/java/competition/simulation/elevator/ElevatorSimulator.java

ElevatorSim: fix values to align with real robot ratios

---

build.gradle

Versioning & Credentials
-----

Vision bezier version & Changing credentials to reliable source

---

src/main/java/competition/subsystems/coral_arm/CoralArmSubsystem.java

Converted rotation values back to degrees for target and current values

---

src/main/java/competition/Robot.java
src/main/java/competition/injection/components/BaseRobotComponent.java
src/main/java/competition/operator_interface/OperatorInterface.java

Verified rumbling stopped locally
-----

add gamepad rumbling to robot.periodic

---

src/main/java/competition/operator_interface/OperatorCommandMap.java

preferred basic operating and driving commandmap

---

src/main/java/competition/subsystems/pose/Landmarks.java

small changes to the coral station poses

---

vendordeps/REVLib.json

Update SCL and RevLib

---

src/main/java/competition/operator_interface/OperatorCommandMap.java
src/main/java/competition/subsystems/drive/commands/AlignToReefWithAprilTagCommand.java
src/main/java/competition/subsystems/drive/commands/AlignToTagGlobalMovementWithCalculator.java
src/main/java/competition/subsystems/pose/Cameras.java
src/main/java/competition/subsystems/vision/AprilTagVisionSubsystemExtended.java

Enum for cameras

---

src/main/java/competition/simulation/coral_arm/CoralArmSimulator.java
src/main/java/competition/subsystems/coral_arm/CoralArmSubsystem.java

Add safeties to Coral Arm

---

src/main/java/competition/simulation/MapleSimulator.java

Update SCL supporting swerve calibration, consume ratios in simulator

---

src/main/java/competition/operator_interface/OperatorCommandMap.java

add calibration to operator gamepad

---

build.gradle
src/main/java/competition/Robot.java
src/main/java/competition/electrical_contract/Contract2025.java
src/main/java/competition/electrical_contract/RoboxContract.java
src/main/java/competition/injection/components/BaseRobotComponent.java
src/main/java/competition/operator_interface/OperatorCommandMap.java
src/main/java/competition/simulation/MapleSimulator.java
src/main/java/competition/subsystems/algae_arm/AlgaeArmSubsystem.java
src/main/java/competition/subsystems/algae_arm/commands/SetAlgaeArmSetpointToTargetPosition.java
src/main/java/competition/subsystems/algae_collection/AlgaeCollectionSubsystem.java
src/main/java/competition/subsystems/coral_arm/CoralArmSubsystem.java
src/main/java/competition/subsystems/coral_scorer/CoralScorerSubsystem.java
src/main/java/competition/subsystems/drive/commands/DebugSwerveModuleCommand.java
src/main/java/competition/subsystems/elevator/ElevatorSubsystem.java
src/main/java/competition/subsystems/elevator/commands/ElevatorMaintainerCommand.java
src/main/java/competition/subsystems/vision/AlignCameraToAprilTagCalculator.java

More changes needed to get the robot online
* Robot loop timing goes from 0.02s->0.04s (our code is too slow)
* Contract updates (likely breaks 2023/2024 contracts)
* Various properties getting hardcoded
* Algae Arm now has proper ratios and PID values
* Algae Arm setpoint commands
* DebugSwerveModule commands now work (correctly requires all swerve components)
* Elevator only auto-calibrates once
* AlignToAprilTag no longer runs to 0,0 if it loses its target.
-----

2025-02-16 Robot Bringup

---

src/main/java/competition/operator_interface/OperatorCommandMap.java

*** Eventually, I want to maybe have some of the buttons as hold buttons rather than everything toggle, but I feel like this is probably the safest way to test out and use the algae system right now
-----

mapped algae buttons

---

src/main/java/competition/operator_interface/OperatorCommandMap.java
src/main/java/competition/subsystems/algae_arm/commands/ForceAlgaeArmCalibrated.java
src/main/java/competition/subsystems/coral_arm/commands/ForceCoralPivotCalibrated.java
src/main/java/competition/subsystems/elevator/commands/ForceElevatorCalibratedCommand.java

Set runs when disabled as true for algae arm, coral arm, and elevator. Adjusted POVs on gamepad

---

azure-pipelines.yml
src/main/java/competition/operator_interface/OperatorCommandMap.java

Cache dependencies on robot build

---

src/main/java/competition/subsystems/algae_arm/AlgaeArmSubsystem.java

Add default PID properties to Algae Arm pivot motor initialization

---

azure-pipelines.yml

Update to latest Git checkout syntax to hopefully checkout faster

---

Elastic/elastic-layout.json
src/main/java/competition/Robot.java
src/main/java/competition/electrical_contract/Contract2025.java
src/main/java/competition/motion/ComplimentaryFilter.java
src/main/java/competition/operator_interface/OperatorCommandMap.java
src/main/java/competition/subsystems/algae_arm/AlgaeArmSubsystem.java
src/main/java/competition/subsystems/coral_arm/commands/CoralArmMaintainerCommand.java
src/main/java/competition/subsystems/coral_scorer/CoralScorerSubsystem.java
src/main/java/competition/subsystems/drive/commands/SwerveDriveWithJoysticksCommand.java
src/main/java/competition/subsystems/elevator/ElevatorSubsystem.java
src/main/java/competition/subsystems/elevator/commands/ElevatorMaintainerCommand.java
src/main/java/competition/subsystems/elevator/commands/ForceElevatorCalibratedCommand.java

* Initial Elastic dashboard
* Fix various issues with electrical contract
* Sensor fusion (including Complimentary Filter)
* All calibration happens at once with the start button
* Various property defaults
* Fix joystick deadband & scaling
* New way of driving the elevator given the fused sensor data
* 
-----

2025-02-18 Robot Bringup

---

build.gradle

**Allowing programming to "contact" vision co processors (orin) easily while having minimum changes Programming side. (Uses a DIRECT connection, RIO -> ORIN for least latency possible. Zero Network Tables)**
```java
VisionCoprocessorCommander commander = new VisionCoprocessorCommander(VisionCoprocessor.ORIN2); // Connect to ORIN-2 
XTableValues.BezierCurves curves = commander
.requestBezierPathWithOptions(XTableValues.RequestVisionCoprocessorMessage.newBuilder()
.setStart(XTableValues.ControlPoint.newBuilder()
.setY(3) // Set Pose2d Y value.
.setX(2) // Set Pose2d X value.
.build())
.setEnd(XTableValues.ControlPoint.newBuilder()
.setX(0) // Set goal Pose2d X value.
.setY(3) // Set goal Pose2d Y value.
.setRotationDegrees(2) // Set goal rotation.
.build())
.setSafeDistanceInches(3) // Will …
```

Small Version Change for Programming -> Vision function calling

---

src/main/java/competition/electrical_contract/Contract2025.java
src/main/java/competition/electrical_contract/ElectricalContract.java
src/main/java/competition/subsystems/SubsystemDefaultCommandMap.java
src/main/java/competition/subsystems/climber/ClimberSubsystem.java
src/main/java/competition/subsystems/climber/commands/ClimbWithJoySticksCommand.java
src/main/java/competition/subsystems/climber/commands/ClimberStopCommand.java
src/main/java/competition/subsystems/coral_arm/commands/CoralArmMaintainerCommand.java

Created the skeleton for ClimberSubsystem

---

src/main/java/competition/electrical_contract/Contract2025.java
src/main/java/competition/subsystems/vision/AlignCameraToAprilTagCalculator.java
src/main/java/competition/subsystems/vision/AprilTagVisionSubsystemExtended.java

So we don't change our heading and all of a sudden we lose our tag target
https://github.com/user-attachments/assets/6f0ce98c-0848-4194-92e8-56315385c312
-----

Will stalk april tag until it gets near (terminal approach fix)

---

Elastic/autonomous-selection-layout.json

autonomous selection layout

---

src/main/java/competition/simulation/elevator/ElevatorSimulator.java

Add laserCan readout to the simulator

---

src/main/java/competition/subsystems/drive/commands/SwerveDriveWithJoysticksCommand.java

Remove two-layer deadbands via newer SCL, and smoother scaling on joysticks

---

src/main/java/competition/operator_interface/OperatorCommandMap.java
src/main/java/competition/subsystems/drive/DriveSubsystem.java
src/main/java/competition/subsystems/drive/commands/DriveToLocationWithPID.java
src/main/java/competition/subsystems/drive/commands/RotateToHeadingWithHeadingModule.java
src/main/java/competition/subsystems/pose/commands/ResetPoseCommand.java

Swerve simple trajectory field testing

---

src/main/java/competition/operator_interface/OperatorCommandMap.java
src/main/java/competition/subsystems/drive/commands/CalibrateDriveCommand.java
src/main/java/competition/subsystems/elevator/commands/ElevatorMaintainerCommand.java

Fix elevator & better drive calibration

---

Elastic/field-testing.json

Click to run command; save time for Sunday
-----

Field Testing Elastic Command Layout

---

src/main/java/competition/electrical_contract/Contract2025.java
src/main/java/competition/electrical_contract/ElectricalContract.java
src/main/java/competition/electrical_contract/UnitTestContract2025.java
src/main/java/competition/operator_interface/OperatorCommandMap.java
src/main/java/competition/subsystems/coral_arm/CoralArmSubsystem.java
src/main/java/competition/subsystems/coral_arm/commands/ForceCoralArmCalibratedCommand.java
src/main/java/competition/subsystems/coral_scorer/CoralScorerSubsystem.java

Created calibration routine for the coral arm

---

src/main/java/competition/commandgroups/PrepAlgaeSystemCommandGroupFactory.java
src/main/java/competition/operator_interface/OperatorCommandMap.java

Preferred controller/button bindings
Changed AlgaeCommands to ButtonCommads in OperatorCommandMap and made PrepAlgaeSystemCommandFactory use providers now
-----

DriverBindings

---

src/main/java/competition/commandgroups/PrepAlgaeSystemCommandGroupFactory.java
src/main/java/competition/operator_interface/OperatorCommandMap.java

Added stopping collection to retracted position for algae arm

---

src/main/java/competition/operator_interface/OperatorCommandMap.java
src/main/java/competition/subsystems/drive/commands/AlignToReefWithAprilTagCommand.java
src/main/java/competition/subsystems/pose/PoseSubsystem.java

Allows for easy branch alignment
OperatorCommandMap, AlignToReefWithAprilTagCommand, PoseSubsystem
https://github.com/user-attachments/assets/147c664a-1043-4192-9859-1843879ae9eb
-----

DriverRelativeBranchAlignment

---

src/main/java/competition/motion/ComplimentaryFilter.java
src/main/java/competition/simulation/elevator/ElevatorSimulator.java
src/main/java/competition/subsystems/elevator/ElevatorSubsystem.java
src/main/java/competition/subsystems/elevator/commands/ElevatorMaintainerCommand.java

Fix elevator in simulator
-----

Fix elevator in simulator

---

src/main/java/competition/simulation/MapleSimulator.java

This used to work, but regressed at some point.
-----

Have the simulated robot start with coral loaded

---

vendordeps/Phoenix5.json

Support Victor SPX

---

src/main/java/competition/subsystems/climber/commands/ClimbWithJoySticksCommand.java

There were a bajillion things using operatorGamepad
Asana task URL: https://app.asana.com/1/2086102074315/project/1208731987242938/task/1209547157518154
-----

Uses superstructure gamepad and added deadband

---

src/main/java/competition/subsystems/drive/logic/AlignCameraToAprilTagCalculator.java

Update alignment defaults, improve alignment scaling

---

src/main/java/competition/simulation/coral_arm/CoralArmSimConstants.java
src/main/java/competition/subsystems/coral_arm/CoralArmSubsystem.java
src/main/java/competition/subsystems/coral_arm/commands/CoralArmMaintainerCommand.java

- add new angle specific for l4 for coral arm
- prevent coral arm from going too far if we're not high enough yet
https://github.com/user-attachments/assets/ad63f483-353e-48d2-9226-6e7f72c35100
-----

Coral arm level 4 angle + safety update

---

src/main/java/competition/operator_interface/OperatorInterface.java
src/main/java/competition/subsystems/algae_arm/AlgaeArmSubsystem.java
src/main/java/competition/subsystems/climber/ClimberSubsystem.java
src/main/java/competition/subsystems/coral_arm/CoralArmSubsystem.java
src/main/java/competition/subsystems/elevator/ElevatorSubsystem.java

start marking less often tuned props as debug only

---

src/main/java/competition/operator_interface/OperatorCommandMap.java

Each of these commands uses up 7 keys in the network tables, so this saves ~70 keys.
-----

remove some lesser unused commands from smartdashboard

---

src/main/java/competition/electrical_contract/Contract2025.java
src/main/java/competition/operator_interface/OperatorCommandMap.java
src/main/java/competition/subsystems/algae_arm/AlgaeArmSubsystem.java

Algae arm testing

---

src/main/java/competition/subsystems/coral_arm/commands/CoralArmMaintainerCommand.java
src/main/java/competition/subsystems/elevator/commands/ElevatorMaintainerCommand.java

To speed up autonomous mode by ~0.1s * 3 = ~0.3s
-----

Loosen Arm + Elevator maintainer error stable criteria

---

src/main/java/competition/electrical_contract/ElectricalContract.java
src/main/java/competition/subsystems/drive/DriveSubsystem.java

Use new SCL with no drive slewing (fixes "shove forever" bugs in autonomous)
-----

Use SCL with no drive slewing

---

src/main/java/competition/operator_interface/OperatorCommandMap.java
src/main/java/competition/subsystems/drive/commands/AlignToNearestCoralStationCommand.java
src/main/java/competition/subsystems/pose/PoseSubsystem.java

Aligns to nearest coral station
PoseSubsystem, OperatorCommandMap
-----

AlignToNearestCoralStationCommand

---

AdvantageScope/StandardLayout.json

Delete debugging tabs

---

src/main/java/competition/subsystems/drive/logic/AlignCameraToAprilTagCalculator.java

https://github.com/user-attachments/assets/4f956608-d039-44f0-a3ec-200ec293ac92
-----

Fix aligning to red alliance coral stations

---

src/main/java/competition/operator_interface/OperatorCommandMap.java

cleaned up driver commands in OperatorCommandMap
-----

PointAtNearestCoralStation

---

src/main/java/competition/commandgroups/DriveToReefFaceThenAlignCommandGroupFactory.java

Disabling retries for auto

---

src/main/java/competition/Robot.java

Algae Arm Calibration On Autonomous Init

---

src/main/java/competition/operator_interface/OperatorCommandMap.java
src/main/java/competition/subsystems/drive/logic/AlignCameraToAprilTagCalculator.java

Gives feedback to drivers to drop the superstructure when robot is retrying its alignment.
-----

RumbleOnRetry

---

src/main/java/competition/commandgroups/DriveToStationAndIntakeUntilCollectedCommandGroupFactory.java
src/main/java/competition/subsystems/drive/commands/ShoveCoralStationCommand.java

Sometimes at the end of auto we don't quite make it to the coral station. In that case, just keep driving until you get one.
-----

Shove until Coral Collected

---

src/main/java/competition/subsystems/drive/logic/AlignCameraToAprilTagCalculator.java

Small stuff to resolve my OCD
-----

AlignCameraToAprilTagCalculator micro optimization

---

src/main/java/competition/subsystems/drive/commands/ShoveCoralStationCommand.java

ShoveCoralStationCommand with units

---

src/main/java/competition/electrical_contract/Contract2024.java

Fix contract on 2024 bot
-----

Update SCL to properly use cached AKit inputs

---

src/main/java/competition/Robot.java
src/main/java/competition/motion/TrapezoidProfileManager.java
src/main/java/competition/simulation/MapleSimulator.java
src/main/java/competition/simulation/SimulationConstants.java
src/main/java/competition/simulation/algae_arm/AlgaeArmSimulator.java
src/main/java/competition/simulation/coral_arm/CoralArmSimulator.java
src/main/java/competition/simulation/elevator/ElevatorSimulator.java
src/test/java/competition/motion/TrapezoidProfileManagerTest.java

We had this info copied all over the place and it really should stay in sync
-----

use a global const for robot loop interval

---

src/main/java/competition/electrical_contract/Contract2025.java
src/main/java/competition/subsystems/coral_arm/CoralArmSubsystem.java

Coral arm hard stop update

---

src/main/java/competition/operator_interface/OperatorCommandMap.java
src/main/java/competition/subsystems/elevator/ElevatorSubsystem.java
src/main/java/competition/subsystems/elevator/commands/TrimElevatorDown.java
src/main/java/competition/subsystems/elevator/commands/TrimElevatorUp.java

Elevator offset trim

---

src/main/java/competition/subsystems/coral_arm/CoralArmSubsystem.java

Super small number change

---

src/main/java/competition/Robot.java
src/main/java/competition/auto_programs/FromCageScoreOneCoralAutoFactory.java
src/main/java/competition/auto_programs/FromLeftCageScoreLeftFacesLevelFours.java
src/main/java/competition/auto_programs/FromRightCageScoreRightFacesLevelFours.java
src/main/java/competition/operator_interface/OperatorCommandMap.java
src/main/java/competition/simulation/reef/ReefSimulator.java

Reducing robot init time

---

src/main/java/competition/subsystems/elevator/commands/ElevatorMaintainerCommand.java

Updated default values for elevator

---

src/main/java/competition/subsystems/coral_arm/CoralArmSubsystem.java
src/main/java/competition/subsystems/coral_arm/commands/CoralArmMaintainerCommand.java

These are the hand tuned values from manual testing copied in from this other pr https://github.com/Team488/TeamXbot2025/pull/296/
-----

CoralArm: Update angles from hardstop moving

---

src/main/java/competition/aspects/CommandTracer.java

Log command execution times

---

src/main/java/competition/Robot.java

handle sim being null in Robot auton init

---

build.gradle

AspectJ copies the SCL files to the
-----

Fix handling SCL updates

---

build.gradle
src/main/java/competition/Robot.java
src/main/java/competition/injection/components/BaseRobotComponent.java
src/main/java/competition/subsystems/coral_arm/CoralArmSubsystem.java

Previously we were violating rules
-----

Coral arm calibration autonomous

---

src/main/java/competition/commandgroups/DriveToFaceAndScoreCommandGroupFactory.java
src/main/java/competition/subsystems/coral_arm/CoralArmSubsystem.java
src/main/java/competition/subsystems/drive/commands/vision_path/SwerveBezierTrajectoryBase.java
src/main/java/competition/subsystems/drive/logic/AlignCameraToAprilTagCalculator.java
src/main/java/competition/subsystems/elevator/ElevatorSubsystem.java

Tuned Constant Persistent Values

---

src/main/java/competition/subsystems/drive/logic/AlignCameraToAprilTagCalculator.java

We should now enter stall properly

---

src/main/java/competition/operator_interface/OperatorCommandMap.java
src/main/java/competition/subsystems/elevator/ElevatorSubsystem.java
src/main/java/competition/subsystems/pose/Landmarks.java

New properties for elevator algae removal heights
-----

New Properties for elevator algae removal heights

---

src/main/java/competition/auto_programs/FromCageScoreOneCoralAutoFactory.java
src/main/java/competition/auto_programs/FromLeftCageScoreLeftFacesLevelFours.java
src/main/java/competition/auto_programs/FromRightCageScoreRightFacesLevelFours.java
src/main/java/competition/commandgroups/DriveToClosestStationCommandGroupFactory.java
src/main/java/competition/commandgroups/DriveToStationAndIntakeUntilCollectedCommandGroupFactory.java
src/main/java/competition/commandgroups/HumanLoadUntillCoralCollectedCommandGroup.java
src/main/java/competition/commandgroups/vision_path/PathDriveToCoralStationAndIntakeUntilCollected.java
src/main/java/competition/commandgroups/vision_path/PathDriveToLocationForCoralStationFactory.java
src/main/java/competition/operator_interface/OperatorCommandMap.java
src/main/java/competition/subsystems/coral_arm/CoralArmSubsystem.java
src/main/java/competition/subsystems/elevator/ElevatorSubsystem.java
src/main/java/competition/subsystems/oracle/OracleSubsystem.java
src/main/java/competition/subsystems/pose/Landmarks.java

COLLECTING --> CORALCOLLECTING

---

src/main/java/competition/operator_interface/OperatorCommandMap.java
src/main/java/competition/subsystems/drive/commands/AlignToNearestReefFaceForAlgaeCommand.java

Algae handling will require us to flip 180 degrees
-----

Flip align to reef face 180 degrees

---

src/main/java/competition/electrical_contract/Contract2025.java
src/main/java/competition/electrical_contract/ElectricalContract.java

Removed climber mentioned in electrical

---

src/main/java/competition/auto_programs/vision/LeftFourCoralAuto.java
src/main/java/competition/auto_programs/vision/RightFourCoralAuto.java
src/main/java/competition/commandgroups/DriveToFaceAndScoreCommandGroupFactory.java
src/main/java/competition/commandgroups/vision_path/PathDriveToLocationForCoralStationFactory.java
src/main/java/competition/electrical_contract/Contract2025.java
src/main/java/competition/operator_interface/OperatorCommandMap.java
src/main/java/competition/subsystems/coral_scorer/CoralScorerSubsystem.java
src/main/java/competition/subsystems/drive/commands/AlignToReefWithAprilTagCommand.java
src/main/java/competition/subsystems/drive/commands/vision_path/DriveVectorSmallCommand.java
src/main/java/competition/subsystems/drive/commands/vision_path/PathDriveToLocationCommand.java
src/main/java/competition/subsystems/drive/logic/AlignCameraToAprilTagCalculator.java
src/main/java/competition/subsystems/elevator/ElevatorSubsystem.java
src/main/java/competition/subsystems/pose/Landmarks.java
src/main/java/competition/subsystems/pose/vision/Paths.java

tune values -11 inches into coral station, this way it starts slowing down perfectly into the coral station then backs in as another precaution
-----

tune -11 inches from robot bumper

---

src/main/java/competition/subsystems/drive/commands/vision_path/SwerveBezierTrajectoryCommand.java

Migrate to variants of interfaces that avoid boxing

---

src/main/java/competition/simulation/MapleSimulator.java

Use Measure system in XGyro

---

src/main/java/competition/subsystems/elevator/ElevatorSubsystem.java
src/main/java/competition/subsystems/vision/CoprocessorCommunicationSubsystem.java

not mark motion magic as debug

---

src/main/java/competition/subsystems/pose/PoseSubsystem.java

Preemptively compute poses

---

src/main/java/competition/subsystems/coral_arm/CoralArmSubsystem.java
src/main/java/competition/subsystems/elevator/ElevatorSubsystem.java

Tuned elevator and coral arm values

---

src/main/java/competition/commandgroups/DriveToClosestStationCommandGroupFactory.java
src/main/java/competition/subsystems/drive/commands/DriveToBargeCommand.java
src/main/java/competition/subsystems/drive/commands/DriveToCoralStationCommand.java
src/main/java/competition/subsystems/drive/commands/vision_path/PathDriveToBargeCommand.java
src/main/java/competition/subsystems/drive/commands/vision_path/SwerveBezierTrajectoryBase.java
src/main/java/competition/subsystems/vision/CoprocessorCommunicationSubsystem.java

[Screencast from 2025-04-02 00-57-24.webm](https://github.com/user-attachments/assets/1a1a5928-4092-45c9-ad29-fb6b50694c73)
drive to barge 
-----

Fix drive to barge & fix coprocessor

---

src/main/java/competition/commandgroups/DriveToFaceAndScoreCommandGroupFactory.java
src/main/java/competition/operator_interface/OperatorCommandMap.java
src/main/java/competition/subsystems/coral_scorer/CoralScorerSubsystem.java

Alignment tuning

---

src/main/java/competition/subsystems/pose/PoseSubsystem.java

Use methods to select pose  estimator

---

src/main/java/competition/electrical_contract/Contract2025.java

Fix back camera

---

src/main/java/competition/Robot.java
src/main/java/competition/subsystems/pose/PoseSubsystem.java

Reverting auto setting deadwheels.

---

src/main/java/competition/electrical_contract/Contract2025.java

Just validated that it won't be stuck spinning anymore.
-----

Using exclude on cameras to filter for poses.
