src/main/java/competition/simulation/MapleSimulator.java
Render the game pieces that maple-sim keeps track of. Right now it's just the starting pieces but it's a start.
-----
=> Feature/maple sim: gamepieces

AdvantageScope/custom_assets/Robot_Xbot2025/config.json
To help visualize our robot (vs the kitbot)
Adds custom assets folder in repo that has 2025 robot in it
This is the current assembly as 1 big model, and it's missing bumpers.
Longer term would be nice to have the elevator separate so we could show it moving up and down (and maybe the arm rotating too).
I'm also not sure what the 'front' is, might need to do some rotating
-----
=> AdvantageScope: xbot 2025 model

src/main/java/competition/simulation/MapleSimulator.java, src/main/java/competition/subsystems/pose/PoseSubsystem.java
Added a switch to use vision assisted pose vs odometry only pose.
-----
=> Allow using Vision pose as the source of robot pose, and pipe it through to simulator

src/main/java/competition/simulation/arm/ArmSimConstants.java, src/main/java/competition/simulation/arm/ArmSimulator.java
Allow students to program the arm and see it move
There's a big problem where the frame of reference doesn't line up, gravity isn't being applied correctly.
In simulator:
https://github.com/user-attachments/assets/480c9d60-f372-4101-b36f-ddf6149dec87
-----
=> ElevatorMechanism: have arm show state from ArmSim

src/main/java/competition/subsystems/algae_collection/AlgaeCollectionSubsystem.java, src/main/java/competition/subsystems/arm_pivot/ArmPivotSubsystem.java, src/main/java/competition/subsystems/coral_scorer/CoralScorerSubsystem.java, src/main/java/competition/subsystems/drive/DriveSubsystem.java, src/main/java/competition/subsystems/elevator/ElevatorSubsystem.java
Implement the new way that subsystems can register their dataframe refreshables. Adds it to a few subsystems that were missing it before too.
-----
=> Subsystem refreshables

src/main/java/competition/subsystems/drive/commands/DebugSwerveModuleCommand.java
Two primary fixes -
1. Require the drive subsystem
2. Apply a deadband on the joysticks
-----
=> Fix DebugSwerveModuleCommand

azure-pipelines.yml
stacktrace is not really useful, since it spits out internal gradle stacks.
-----
=> Change Gradle logging on builds to make it easier to find failures

.github/pull_request_template.md, src/main/java/competition/motion/TrapezoidProfileManager.java, src/main/java/competition/simulation/elevator/ElevatorSimulator.java, src/main/java/competition/subsystems/elevator/ElevatorSubsystem.java, src/main/java/competition/subsystems/elevator/commands/ElevatorMaintainerCommand.java
To enable smoother control of the elevator leverage https://docs.wpilib.org/en/stable/docs/software/advanced-controls/controllers/trapezoidal-profiles.html to limit the velocity and acceleration of system changes.
The goal here is to make this really easy to use so it's trivial to put it in our 3 positional systems (elevator, coral arm, pivot arm).
- Adds a new wrapper class for the wpilib trapezoid profile so that we can tune it with our Property system and plug it into our current pid logic easily
- This could be used with an on rio PID for position (as it is here) or the positional setpoint could just as easily be set on the motor controller itself
- Should this live in the SetpointSubsystem instead perhaps? I just started in the maintainer because that's where the pid …
=> Trapezoid motion control for elevator

src/main/java/competition/operator_interface/OperatorCommandMap.java, src/main/java/competition/operator_interface/OperatorInterface.java, src/main/java/competition/subsystems/drive/DriveSubsystem.java
We need a practical SysId example to try it out.
Add a SysId gamepad to allow us to tune the pids for the robot drive.
-----
=> Add SysId routines for the Swerve drive

src/main/java/competition/operator_interface/OperatorCommandMap.java, src/main/java/competition/operator_interface/OperatorInterface.java, src/main/java/competition/subsystems/algae_arm/commands/AlgaeArmMaintainerCommand.java, src/main/java/competition/subsystems/coral_arm_pivot/commands/CoralArmPivotMaintainerCommand.java, src/main/java/competition/subsystems/drive/commands/DebugSwerveModuleCommand.java, src/main/java/competition/subsystems/drive/commands/SwerveDriveWithJoysticksCommand.java, src/main/java/competition/subsystems/drive/commands/TankDriveWithJoysticksCommand.java, src/main/java/competition/subsystems/elevator/commands/ElevatorMaintainerCommand.java
New pattern for gamepads:
- 1) Driver
- 2) Operator (xbox controller)
- 3) Neotrellis
- 4) OI Panel
- 5) ManualOverrides - Superstructure (Elevator, Arm)
- 6) ManualOverrides - AlgaeArm and SysId
-----
=> Move to clear responsibilities for gamepads

src/main/java/competition/electrical_contract/Contract2025.java, src/main/java/competition/electrical_contract/ElectricalContract.java, src/main/java/competition/operator_interface/OperatorCommandMap.java, src/main/java/competition/subsystems/drive/commands/AlignToReefWithAprilTagCommand.java
Align to Reef had a few bugs, most critically relating to reusing PID for X and Y rather than PID'ding on a unified vector. Moved that key logic to the SCL and using it here.
* Robot now tracks its perimeter in the ElectricalContract
* AlignToReef extra logging
* AlignToReef debugged core motion logic
-----
=> Align to reef fixes

src/main/java/competition/simulation/MapleSimulator.java, src/main/java/competition/simulation/reef/ReefSimulator.java, src/main/java/competition/subsystems/elevator/SuperstructureMechanism.java
To make the simulated environment more realistic, we'll now:
- require that the robot be more lined up with a reef post to score (otherwise it drops to the ground)
- require that there not already be coral on that reef (otherwise it drops to the ground)
- require that the robot be aligned with the human loading station to get fresh coral
I also have some code locally that map useful operator buttons to the driver gamepad to make solo driving easier, might be nice to include in main for now?
https://github.com/user-attachments/assets/5f4c3463-bdd3-4e6f-bac1-998675899967
-----
| …
=> Simulator: more accurate coral scoring/loading

src/main/java/competition/Robot.java, src/main/java/competition/injection/components/SimulationComponent.java, src/main/java/competition/injection/modules/SimulatedRobotModule.java, src/test/java/competition/SimulatedRobotTest.java
Our most common programming bug is if the robot code doesn't start for some reason or another.
Adds a unti test to start the simulator with some different contract settings to test that the robot starts successfully.
-----
=> Add a unit test to verify that the robot can start in disabled mode

src/main/java/competition/operator_interface/OperatorCommandMap.java
We're often testing the robot out solo with 1 gamepad. The driver gamepad is using almost no buttons at this point so I thought it would be helpful to give it a couple of common coral scoring ones for now.
-----
=> Add some coral system commands to driver gamepad

src/main/java/competition/injection/components/CompetitionTestComponent.java, src/main/java/competition/injection/modules/UnitTestRobotModule.java, src/test/java/competition/BaseCompetitionTest.java, src/test/java/competition/subsystems/drive/DriveSubsystemDisabledTest.java, src/test/java/competition/subsystems/drive/DriveSubsystemTest.java
Bugs related to electrical contract isReady flags are one of the most common sources of robot code bugs.
Add a sample unit test that makes sure a subsystem doesn't crash even when its components are not ready yet.
-----
=> Add a unit test with the drive marked as not ready

src/main/java/competition/subsystems/elevator/ElevatorSubsystem.java, src/test/java/competition/subsystems/elevator/ElevatorSubsystemDisabledTest.java
We need to guard against missing elevator components so that robots don't crash.
Add guards and a test for breaking the guards
-----
=> Add missing guards in elevator code

src/main/java/competition/subsystems/elevator/commands/ElevatorMaintainerCommand.java
Theres no sensor on the robot right now, so it continuously applies downforce to try and calibrate even when its at the bottom, this is to prevent that for testing pursposes.
- [x ] tested in simulator
-----
=> Dont allow calibration without sensor

build.gradle, src/main/java/competition/simulation/coral_arm/CoralArmSimConstants.java, src/main/java/competition/simulation/coral_arm/CoralArmSimulator.java, src/main/java/competition/subsystems/coral_arm/CoralArmSubsystem.java
John hacked away the coral arm working in angles and instead it works in rotations right now. This totally borked the sim logic. This PR makes the arm work in the sim (though the robots sense of where the arm is is still kinda messed up).
-----
=> CoralArmSim: Fix for changes made for real robot

src/main/java/competition/simulation/coral_arm/CoralArmSimConstants.java
This was added to simulate how the arm was hanging under the collection point, but now there's a hardstop on the robot so that behavior has gone away and we can go back to calibration at the start position as 0
-----
=> revert change to have robot coral arm start lower than collection point

src/main/java/competition/motion/TrapezoidProfileManager.java, src/main/java/competition/subsystems/algae_arm/commands/AlgaeArmMaintainerCommand.java, src/main/java/competition/subsystems/coral_arm/commands/CoralArmMaintainerCommand.java, src/main/java/competition/subsystems/elevator/commands/ElevatorMaintainerCommand.java, src/test/java/competition/motion/TrapezoidProfileManagerTest.java
and only use it on reset if it's been recently used.
This fixes the bug where after disabling the robot and the elevator drops down, when you renable it it was using the previous setpoint to start the profile.
-----
=> Trapezoid profile manager: store prev setpoint internally 

src/main/java/competition/electrical_contract/Contract2025.java
Swerve module math depends on the positions of each swerve module in space.
On the 2025 robot, the wheels are spaced 24" apart (center to center) in a square arrangement.
Adjusted the swerve module positions to reflect the 24" spacing on the 2025 robot.
Updated SCL after verifying on 2024 robot.
-----
=> Fix swerve module positions for 2025 and update SCL

src/main/java/competition/electrical_contract/Contract2024.java, src/main/java/competition/electrical_contract/Contract2025.java
Each of our robots has different swerve module gear ratios. We want to generate the default scaling values from the physical parameters rather than reverting to obviously wrong numbers if properties are lost.
-----
=> Calibrate swerve drive from contract

src/main/java/competition/subsystems/algae_arm/AlgaeArmSubsystem.java, src/main/java/competition/subsystems/algae_arm/commands/AlgaeArmMaintainerCommand.java
To continuously calibrate the algae arm whenever it hits the low sensor. Also I moved the manual algae arm control to the operator gamepad.
AlgaeArmSubsytem, AlgaeArmMaintainerCommand
-----
=> AlgaeArm Continous Calibration

src/main/java/competition/motion/TrapezoidProfileManager.java, src/main/java/competition/subsystems/elevator/commands/ElevatorMaintainerCommand.java, src/test/java/competition/motion/TrapezoidProfileManagerTest.java
The elevator has some unexpected motion when enabling after disable.
Explicitly reset the state on initializing the maintainer or starting machine control.
-----
=> Attempt to fix elevator jerkiness on enable/disable

src/main/java/competition/commandgroups/DriveToFaceAndScoreCommandGroupFactory.java, src/main/java/competition/commandgroups/DriveToStationAndIntakeUntilCollectedCommandGroupFactory.java, src/main/java/competition/commandgroups/HeadingAssistedDriveAndScoreCommandGroup.java, src/main/java/competition/commandgroups/HumanLoadUntillCoralCollectedCommandGroup.java, src/main/java/competition/commandgroups/PrepCoralSystemCommandGroupFactory.java, src/main/java/competition/operator_interface/OperatorCommandMap.java, src/main/java/competition/subsystems/coral_arm/CoralArmSubsystem.java, src/main/java/competition/subsystems/coral_arm/commands/SetCoralArmTargetAngleCommand.java, src/main/java/competition/subsystems/coral_scorer/commands/ScoreWhenReadyCommand.java, src/main/java/competition/subsystems/drive/commands/DriveToReefFaceFromAngleUntilDetectionCommand.java, src/main/java/competition/subsystems/drive/commands/MeasureDistanceBeforeScoringCommand.java, src/main/java/competition/subsystems/pose/PoseSubsystem.java
A new control scheme where the operator sets the target coral level and a driver button will make the robot drive to a target branch and score based on the current robot heading.
PoseSubsystem, PrepCoralSystemCommandGroupFactory, SetCoralArmTargetAngleCommand, 
-----
=> HeadingAssistedDriveAndScore

src/main/java/competition/operator_interface/OperatorCommandMap.java, src/main/java/competition/subsystems/drive/commands/DriveToCoralStationWithVisionCommand.java, src/main/java/competition/subsystems/drive/commands/DriveToWaypointsWithVisionCommand.java, src/main/java/competition/subsystems/vision/CoprocessorCommunicationSubsystem.java, src/test/java/competition/subsystems/drive/DriveToCoralStationWithVisionCommandTest.java
Adding the ability to use Vision path planning to avoid obstacles for designated locations.
Currently set to the only april tag on our setup field, will update to any coral station based on location and which side of the field we are operating on.
Still needs the corresponding code on Alt side.
-----
=> Adding a drive to coral station via vision avoidance system.

src/main/java/competition/subsystems/drive/logic/AlignCameraToAprilTagCalculator.java, src/main/java/competition/subsystems/vision/AprilTagVisionSubsystemExtended.java
If the target tag is no longer the best tag, the robot could lose it. Updated the code to always track a specific tag.
Use the new commands on AprilTagVisionSubsystem to track a specific tag rather than the best.
https://github.com/user-attachments/assets/8f2eeabe-9d57-4026-9b04-867ff793a162
-----
=> When aligning to an April Tag, lock on to a single tag even if it's not the best target

src/test/java/competition/injection/ComponentsTest.java
Students frequently reference the wrong types when doing dependency injection.
Add a test that will fail the build if a forbidden class is injected in a way that will impact a real robot.
-----
=> Add test for Dependency Injection components

src/main/java/competition/simulation/MapleSimulator.java
Makes the sim robot behave a little more realistically, before it was getting coral too fast. Also tighten the distance away it needs to be (was 0.5m which is bananas)
-----
=> Sim update: require the robot to be near the human loading for 1s

src/main/java/competition/simulation/reef/ReefSimulator.java
Was missing checking for alliance to find the right reef locations.
-----
=> Fix reef sim working for red + blue again

src/main/java/competition/commandgroups/DriveToFaceAndScoreCommandGroupFactory.java
measure distance before prepping was debugged on the red side in the sim so i'm adding this back
-----
=> Adding back measure distance before prepping

src/main/java/competition/auto_programs/FromLeftCageScoreLeftFacesLevelFours.java, src/main/java/competition/commandgroups/DriveToReefFaceThenAlignCommandGroupFactory.java, src/main/java/competition/commandgroups/DriveToStationAndIntakeUntilCollectedCommandGroupFactory.java
We were having issues where the robot could only run auto once before needing to restart the robot. The error we were seeing was that we were trying to run/schedule a command that was part of a command composition, but I couldn't find an example of incorrect command creation.
Eventually I looked at `DriveToReefFaceThenAlignCommandGroupFactory`, which is notable in that it is the only place where we have used a `DeferredCommand`. Something about how we were reusing the command to be deferred is causing issues with the scheduler. The solution is to move the creation of the deferred command inside the DeferredCommand's constructor. 
-----
| :star: :star: :star:     | must be …
=> Cleaned up factory issues, and fixed the core "can only do auto once" bug

src/main/java/competition/simulation/MapleSimulator.java
When we doubled our loop time on the core robot, we didn't make a corresponding change in the simulator. This fixes that. Notably, this roughly doubles the velocity of the robot in the sim.
-----
=> Fix simulation timing

src/main/java/competition/auto_programs/BaseAutonomousSequentialCommandGroup.java, src/main/java/competition/auto_programs/FromCageScoreOneCoralAutoFactory.java, src/main/java/competition/auto_programs/FromLeftCageScoreLeftFacesLevelFours.java, src/main/java/competition/auto_programs/FromRightCageScoreRightFacesLevelFours.java
Our auto doesn't do anything visible for the first few cycles. Parallelize several steps to start acting faster.
Moved some init and logging steps to be run in parallel
-----
=> Parallelize parts of auto setup to reduce time to movement start

src/main/java/competition/simulation/reef/ReefSimulator.java
There was a bug in the logic to display the reef on red, it would render the coral on blue still even though it knew it was red.
-----
=> Fix reef sim red side not rendering correctly

.github/CODEOWNERS
Almost all the key areas of the code have a student that primarily worked on it. This will assign them formally as code owners so they'll get added on relevant PRs automatically.
-----
=> Add more specific code owners

build.gradle, src/main/java/competition/aspects/CommandTracer.java
Sample cycle log:
13.469439: execution(Robot.loopFunc())
13.469439: -> SwerveDriveWithJoysticksCommand execution(SwerveDriveWithJoysticksCommand.execute())
13.469439: -> SwerveDriveMaintainerCommand execution(BaseMaintainerCommand.execute())
13.469439: -> SwerveSteeringMaintainerCommand execution(BaseMaintainerCommand.execute())
13.469439: -> SwerveDriveMaintainerCommand execution(BaseMaintainerCommand.execute())
13.469439: -> SwerveSteeringMaintainerCommand execution(BaseMaintainerCommand.execute())
13.469439: -> SwerveDriveMaintainerCommand execution(BaseMaintainerCommand.execute())
13.469439: -> SwerveSteeringMaintainerCommand execution(BaseMaintainerCommand.execute())
13.469439: -> SwerveDriveMaintainerCommand execution(BaseMaintainerCommand.execute())
13.469439: -> …
=> More tracing capability to cover commands defined in SCL and WPILib

src/main/java/competition/aspects/SubsystemTracer.java
We have fishy robot performance issues, so we need more data.
Emit telemetry around all subsystem periodic() and refreshDataFrame() calls
-----
=> Log subsystem times using Advantage Kit

src/main/java/competition/simulation/elevator/ElevatorSimulator.java, src/main/java/competition/subsystems/elevator/ElevatorSubsystem.java, src/main/java/competition/subsystems/elevator/commands/ElevatorMaintainerCommand.java, src/main/java/competition/subsystems/elevator/commands/ForceElevatorCalibratedCommand.java, src/test/java/competition/subsystems/elevator/ElevatorSubsystemDisabledTest.java
LaserCAN updates happen less frequently than the robot code loop. We don't want to calibrate positions off of stale data, so make sure that we only report LaserCAN measurements while they're reasonably fresh.
-----
=> Only consume the freshest LaserCAN updates

src/main/java/competition/subsystems/drive/commands/AlignToReefWithAprilTagCommand.java, src/main/java/competition/subsystems/drive/commands/AlignToTagGlobalMovementWithCalculator.java
When the cameras were off, auto went bananas and just drove forward as fast as it could. It's safer if this just sits there and doesn't move. I opted for it to not end so that it doesn't continue auto (by scoring a coral into mid air)
-----
=> bail on align to reef if the camera isn't connected

src/main/java/competition/operator_interface/OperatorCommandMap.java
We don't want retries to happen when the drivers are aligning because it causes the robot to freak out with the elevator up. This was disabled for Sammamish but reverted (accidentally?) in this PR https://github.com/Team488/TeamXbot2025/pull/259/files#diff-700f6b99e9b967334765c7f668a60223859b3978835f5d423304ea49220ef9f6R94.
-----
=> disable retries again for align to reef

src/main/java/competition/electrical_contract/UnitTestContract2025.java, src/main/java/competition/simulation/coral_arm/CoralArmSimConstants.java, src/main/java/competition/simulation/coral_arm/CoralArmSimulator.java, src/main/java/competition/subsystems/elevator/SuperstructureMechanism.java
- Disable the arm absolute encoder in unit test contract, we don't have the device and probably never will
- Update the superstructure vis so that 0' arm angle is now the new bottom spot
- Change the params of the coral arm sim to match the new positioning
https://github.com/user-attachments/assets/b7b78b84-67e6-4b73-9b22-a8e58b69bdc4
-----
=> Update coral arm in sim and superstructure vis

src/main/java/competition/subsystems/drive/commands/EmergencyAutonomousCommand.java
Emergency auto was trying to drive forward at 100% power which is CRAZY fast, it would almost instantly slam into whatever was infront of it before the drivers have a chance to hit the A-Stop button.
This value will need to be updated on the robot as well.
-----
=> change default value of EmergencyAutoCommand's drive forward power

src/main/java/competition/operator_interface/OperatorCommandMap.java, src/main/java/competition/subsystems/coral_arm/CoralArmSubsystem.java
Grabs @Glowdisk's work from https://github.com/Team488/TeamXbot2025/pull/323 and merges it in to Junyu's elevator height levels.
Changed commands to be setting both elevator height and coral arm angles.
-----
=> Add algea collection angles and merge with elevator height target setting

src/main/java/competition/commandgroups/DriveToReefFaceThenAlignCommandGroupFactory.java, src/main/java/competition/subsystems/pose/PoseSubsystem.java
I want to clean up the Deferred command, but want to check in this unrelated cleanup separately.
Remove unnecessary command group layer.
Use deadwheel pose estimator for snapping vision pose
-----
=> Minor drive to reef face and align cleanup
